[[redirects]]
  from = "/api/*"
  to = "https://project-blogpost.herokuapp.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "https://unruffled-fermi-9ccdf5.netlify.app/:splat"
  status = 200
  